from __future__ import annotations


class FieldCode:
    PROJECT_NAME = "project_name"
    POI_POWER_REQ_MW = "poi_power_req_mw"
    POI_ENERGY_REQ_MWH = "poi_energy_req_mwh"
    PROJECT_LIFE_YEARS = "project_life_years"
    CYCLES_PER_YEAR = "cycles_per_year"
    POI_GUARANTEE_YEAR = "poi_guarantee_year"
    EFF_DC_CABLES = "eff_dc_cables"
    EFF_PCS = "eff_pcs"
    EFF_MVT = "eff_mvt"
    EFF_AC_CABLES_SW_RMU = "eff_ac_cables_sw_rmu"
    EFF_HVT_OTHERS = "eff_hvt_others"
    SC_TIME_MONTHS = "sc_time_months"
    DOD_PCT = "dod_pct"
    DC_ROUND_TRIP_EFFICIENCY_PCT = "dc_round_trip_efficiency_pct"
    RTE_CURVE_ADJUST_PP = "rte_curve_adjust_pp"
    RTE_MONOTONIC_ENFORCE = "rte_monotonic_enforce"
    EFF_DC_TO_POI_FRAC = "eff_dc_to_poi_frac"
    DC_POWER_REQUIRED_MW = "dc_power_required_mw"
    DC_ENERGY_CAPACITY_REQUIRED_MWH = "dc_energy_capacity_required_mwh"
    DC_NAMEPLATE_BOL_MWH = "dc_nameplate_bol_mwh"
    EFFECTIVE_C_RATE = "effective_c_rate"
    SOH_PROFILE_ID = "soh_profile_id"
    RTE_PROFILE_ID = "rte_profile_id"
    ITERATION_COUNT = "iteration_count"
    GUARANTEE_YEAR_POI_USABLE_MWH = "guarantee_year_poi_usable_mwh"
    MARGIN_MWH = "margin_mwh"
