from __future__ import annotations

from calb_sizing_tool.schemas.diagram_inputs import SldRendererMode


DEFAULT_SLD_RENDERER_MODE: SldRendererMode = "engineering_v2"
AVAILABLE_SLD_RENDERER_MODES: tuple[SldRendererMode, ...] = ("engineering_v2",)
PUBLIC_SLD_RENDERER_MODES: tuple[SldRendererMode, ...] = ("engineering_v2",)

#: Modes withdrawn on owner instruction (2026-08-06): "legacy_server 不留;
#: topology_v1 不用了". Both renderers are gone — sld_server_baseline_renderer
#: and sld_pro_renderer — so there is nothing left to dispatch to.
#:
#: sld_layout_engine survived: it looked like topology_v1's alone, but its test
#: module hosts the _build_topology fixture that three LIVE engineering_v2 test
#: files import, and SldLayoutSymbol backs test_symbol_library. Removing it
#: would have meant rewriting live tests to serve a cleanup — the suite caught
#: that and the file went back.
#:
#: They are NAMED here rather than simply forgotten, because the strings outlive
#: the code: every SLD artifact ever generated recorded its renderer_mode in
#: metadata, and a restored run, an external submission or a hand-edited setting
#: can still carry one. Meeting that with an exception would turn old, valid data
#: into a crash. It resolves to the current renderer instead — the drawing is
#: regenerated by today's engine, which is the only engine there is.
RETIRED_SLD_RENDERER_MODES: tuple[str, ...] = ("legacy_server", "topology_v1")

_MODE_LABELS: dict[str, str] = {
    "engineering_v2": "Engineering V2 Professional SLD",
}


def normalize_sld_renderer_mode(value: str | None) -> SldRendererMode:
    """The mode to render in, accepting anything history may hand us.

    A retired mode is mapped to the default rather than rejected — see
    RETIRED_SLD_RENDERER_MODES. An outright unknown string is still an error,
    because that is a caller bug rather than an old record.
    """
    mode = str(value or DEFAULT_SLD_RENDERER_MODE).strip()
    if mode in RETIRED_SLD_RENDERER_MODES:
        return DEFAULT_SLD_RENDERER_MODE
    if mode in AVAILABLE_SLD_RENDERER_MODES:
        return mode  # type: ignore[return-value]
    raise ValueError(f"Unsupported SLD renderer mode: {mode}")


def sld_renderer_mode_label(mode: str) -> str:
    return _MODE_LABELS.get(mode, mode)


def is_sld_renderer_mode_available(mode: str) -> bool:
    return normalize_sld_renderer_mode(mode) in AVAILABLE_SLD_RENDERER_MODES


def is_sld_renderer_mode_public(mode: str) -> bool:
    return normalize_sld_renderer_mode(mode) in PUBLIC_SLD_RENDERER_MODES
