from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from calb_sizing_tool.services.sld_pipeline_service import (
    normalize_sld_render_output,
    normalize_sld_svg,
    prepare_sld_pipeline_from_run_bundle,
    render_prepared_sld_pipeline,
    write_normalized_json,
)
from tests.integration.sld_regression_support import build_case_inputs, load_case_definition

DEFAULT_CASE_DIR = Path("tests/fixtures/sld_cases/case01_container_only_group1")
DEFAULT_OUTPUT_DIR = Path("outputs/sld_renderer_mode_comparison/case01_container_only_group1")
RENDERER_MODES = ("engineering_v2", "legacy_server")


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")


def _display_path(path: Path) -> str:
    try:
        return path.relative_to(PROJECT_ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def _text_set(normalized_svg: dict[str, Any]) -> set[str]:
    return {str(item).strip() for item in normalized_svg.get("text_nodes", []) if str(item).strip()}


def _diff_text_nodes(mode_payloads: dict[str, dict[str, Any]]) -> dict[str, Any]:
    legacy_text = _text_set(mode_payloads["legacy_server"]["normalized_render"]["svg"])
    engineering_v2_text = _text_set(mode_payloads["engineering_v2"]["normalized_render"]["svg"])
    return {
        "engineering_v2_only_vs_legacy": sorted(engineering_v2_text - legacy_text),
        "engineering_v2_removed_from_legacy": sorted(legacy_text - engineering_v2_text),
        "shared_count": len(legacy_text & engineering_v2_text),
    }


def _summary_markdown(case_dir: Path, output_dir: Path, summary: dict[str, Any]) -> str:
    mode_lines = []
    for mode, payload in summary["modes"].items():
        metadata = payload["metadata"]
        mode_lines.append(
            f"| `{mode}` | `{metadata.get('renderer_lineage')}` | "
            f"{payload['svg_element_count']} | {payload['text_node_count']} | "
            f"`{payload['svg_path']}` |"
        )

    text_diff = summary["text_node_diff"]
    engineering_v2_only = "\n".join(f"- {item}" for item in text_diff["engineering_v2_only_vs_legacy"][:30]) or "- None"
    engineering_v2_removed = "\n".join(f"- {item}" for item in text_diff["engineering_v2_removed_from_legacy"][:30]) or "- None"
    return f"""# SLD Renderer Mode Comparison

Case:

```text
{case_dir.as_posix()}
```

Output:

```text
{output_dir.as_posix()}
```

## Rendered Modes

| Mode | Lineage | SVG elements | Text nodes | SVG |
|---|---:|---:|---:|---|
{chr(10).join(mode_lines)}

## Text Present Only In Engineering V2 Compared With Legacy

{engineering_v2_only}

## Legacy Text Removed In Engineering V2

{engineering_v2_removed}

## Interpretation

`legacy_server` is the patched legacy compatibility path, retained only for comparison.
`engineering_v2` is the professional SLD candidate and the default UI mode.
`topology_v1` is retired from the public selector and is not generated by this comparison script.

This generated comparison is for visual review and engineering model design only.
It does not prove that either renderer is the final engineering-readable SLD.
"""


def generate_comparison(case_dir: Path, output_dir: Path) -> dict[str, Any]:
    case_dir = case_dir.resolve()
    output_dir = output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    run_bundle, ac_snapshot, base_options, project_settings = build_case_inputs(load_case_definition(case_dir))
    mode_payloads: dict[str, dict[str, Any]] = {}

    for mode in RENDERER_MODES:
        mode_dir = output_dir / mode
        mode_dir.mkdir(parents=True, exist_ok=True)

        options = base_options.model_copy(update={"renderer_mode": mode})
        prepared = prepare_sld_pipeline_from_run_bundle(
            run_bundle,
            ac_snapshot=ac_snapshot,
            options=options,
            project_settings=project_settings,
        )
        render_output = render_prepared_sld_pipeline(prepared)
        normalized_render = normalize_sld_render_output(render_output)
        normalized_svg = normalize_sld_svg(render_output["svg_bytes"])

        svg_path = mode_dir / "sld.svg"
        png_path = mode_dir / "sld.png"
        metadata_path = mode_dir / "metadata.json"
        normalized_path = mode_dir / "normalized_render.json"
        topology_path = mode_dir / "topology.json"

        svg_path.write_bytes(render_output["svg_bytes"])
        png_path.write_bytes(render_output["png_bytes"])
        _write_json(metadata_path, render_output["metadata"])
        write_normalized_json(normalized_path, normalized_render)
        _write_json(topology_path, render_output["topology"])

        mode_payloads[mode] = {
            "metadata": render_output["metadata"],
            "normalized_render": normalized_render,
            "svg_path": _display_path(svg_path),
            "png_path": _display_path(png_path),
            "metadata_path": _display_path(metadata_path),
            "normalized_render_path": _display_path(normalized_path),
            "topology_path": _display_path(topology_path),
            "svg_element_count": sum(normalized_svg["element_counts"].values()),
            "text_node_count": len(normalized_svg["text_nodes"]),
        }

    summary = {
        "case_dir": _display_path(case_dir),
        "output_dir": _display_path(output_dir),
        "modes": {
            mode: {
                key: value
                for key, value in payload.items()
                if key != "normalized_render"
            }
            for mode, payload in mode_payloads.items()
        },
        "text_node_diff": _diff_text_nodes(mode_payloads),
    }
    _write_json(output_dir / "comparison_summary.json", summary)
    (output_dir / "comparison_summary.md").write_text(
        _summary_markdown(case_dir, output_dir, summary),
        encoding="utf-8",
    )
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate SLD renderer mode comparison artifacts.")
    parser.add_argument("--case-dir", type=Path, default=DEFAULT_CASE_DIR)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    args = parser.parse_args()
    summary = generate_comparison(args.case_dir, args.output_dir)
    print(f"Generated SLD renderer mode comparison under {summary['output_dir']}")


if __name__ == "__main__":
    main()
